### ISSUE TITLE
Border Box issue

### ISSUE THREAD

**Issue by heatherlyall** [heatherlyall/just-your-type#1]
Hi! I can't put a border box around my text it just keeps going across the top @muxlowc

**Comment by muxlowc** [comment]
@heatherlyall 

You might have to add the border to your "bigtext" div and then add a height to it. The reason it looks like there's only a top border is because it doesn't have a height so it's just kind of squishing itself. 

Hope that helps!

**Comment by muxlowc** [comment]
@heatherlyall can you please close this issue if it's resolved? Thanks!
